version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: strongSolarWatchPassword123Docker
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./SolarWatchApi
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=weatherApi;User Id=sa;Password=strongSolarWatchPassword123Docker;TrustServerCertificate=true;"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORTS: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: admin
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    env_file:
      - ./SolarWatchApi/.env
    volumes:
      - $HOME/.aspnet/https:/https/:ro
    depends_on:
      - mssql

  frontend:
    build:
      context: ./SolarWatchWebApp
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:5173"
    environment:
      VITE_API_BASE_URL: "https://localhost:5001"
    volumes:
      - ./SolarWatchWebApp/certs:/app/certs
    depends_on:
      - backend

volumes:
  mssql_data:
